parameters:
    check_pass: '%env(CHECK_PASS_PASSPHRASE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventSubscriber\JwtSessionSubscriber:
        arguments:
            $siteName: '%silversat_permission.site%'

    App\EventListener\MaintenanceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\Service\RedisClient:
        arguments:
            $dsn: '%env(REDIS_DSN)%'
